### ISSUE TITLE
Nested variables?

### ISSUE THREAD

**Issue by AndrewLane** [sankethpb/create-text-file-plugin#1]
Does this support nested variables?

For example if you have
MY_ENVIRONMENT=FOO
MY_DATA_FOO=bar

would

${MY_DATA_${MY_ENVIRONMENT}}

resolve to bar?  I'm trying this and it's not working but not sure if I'm doing it wrong.

**Comment by sankethpb** [comment]
Nested variable support is not available, may I know the usecase?

**Comment by sankethpb** [comment]
Please raise issue in http://issues.jenkins-ci.org/secure/IssueNavigator.jspa?mode=hide&reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27text-file-operations-plugin%27

**Comment by AndrewLane** [comment]
I'm new to scripting in Jenkins, so this was mostly me spit-balling.  I was trying to figure out a solution to the issue of having multiple environment to deploy to (e.g. DEV, TEST, PROD) but wanting only a single set of deployment scripts.  I found that the EnvInject Plugin was a better solution than resorting to nested variables.  This issue can be closed.
